//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DCP.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class AuctionHistory
    {
        public int ID { get; set; }
        public int ProID { get; set; }
        public int UserID { get; set; }
        public decimal PriceBid { get; set; }
        public System.DateTime AuctionTime { get; set; }
        public bool AuctionStatus { get; set; }
        public decimal PriceCur { get; set; }
    }
}
